# Minimal Mistakes skin (pick: air, dark, mint, sunrise, etc.)
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: "The Silicon Standard"
title_separator: "-"
name: "PixelPulse"
description: "An unbiased review of everything related to tech."
url: "https://standardsilicon.github.io"
baseurl: "" # Root, because you’re using a user/organization GitHub Pages site
repository: "standardsilicon/standardsilicon.github.io"

# Example: Uncomment if you have a logo
# logo: "/assets/images/logo.png"

# Navigation Bar
nav:
  - title: "Home"
    url: "/"
  - title: "Reviews"
    url: "/reviews/"
  - title: "Productivity"
    url: "/productivity/"
  - title: "Gaming"
    url: "/gaming/"
  - title: "About"
    url: "/about/"

# Author Info
author:
  name: "PixelPulse"
  bio: "I help you make the best choices about new tech, builds, and everything in between."
  location: "Sammamish, Washington, USA"
  email: "standardsilicon@gmail.com"
  avatar: # Add a path if you want an author profile image
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:standardsilicon@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/standardsilicon"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://standardsilicon.github.io"

# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/standardsilicon"
  since: "2025"

# Reading Files
include:
  - .htaccess
  - _pages

# Markdown + Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Pagination
paginate: 5
paginate_path: /page:num/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

